# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish" # blowfish, avocado, fire, ocean, slate
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["blog"]
# robots = ""
# disableImageOptimization = false

# defaultBackgroundImage = "IMAGE.jpg" # used as default for background images 
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles

# highlightCurrentMenuArea = true
# smartTOC = true
# smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed" # valid options: basic, fixed

[footer]
 # showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, hero, card, background, custom
  homepageImage = "img/Laravel_SPA_Logo.png" # used in: hero, and card
  showRecent = true
  showRecentItems = 9
  showMoreLink = true
  showMoreLinkDest = "blog"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = true # only used when layout equals background

[article]
  showDate = true
  showViews = true
  showLikes = true
  showDateUpdated = false
  showAuthor = true
  showHero = false
  heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true 
  showAuthorsBadges = false 
  showWordCount = true
  showSummary = true
  sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email"]

[list]
  #showHero = true
  #heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  #layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  #layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = false
  showViews = true
  showLikes = true
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  #showHero = true
  #heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  #showBreadcrumbs = true
  showViews = true
  showLikes = true
  #showTableOfContents = true
  cardView = false

[term]
  #showHero = true
  #heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  #showBreadcrumbs = true
  showViews = true
  showLikes = true
  #showTableOfContents = true
  #groupByYear = false
  #cardViewScreenWidth = false
  cardView = false

[firebase]
   apiKey = "AIzaSyAbobgb8uyAa603RBYEpBJ_LkDn_3l5Ack"
   authDomain = "english-blog-b188a.firebaseapp.com"
   projectId = "english-blog-b188a"
   storageBucket = "english-blog-b188a.appspot.com"
   messagingSenderId = "1066772666708"
   appId = "1:1066772666708:web:1e3ce6054fb91ee434d0c1"
   measurementId = "G-WLB7ZNFMCT"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
   identifier = "devmahmoud"
   globalWidget = true
   globalWidgetMessage = "Hello"
   globalWidgetColor = "#FFDD00"
   globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""